In [1]:
import os
from pathlib import Path

import pandas as pd

In [8]:
sent_path = Path(os.environ["SENT_PATH"])
year_path = sent_path / "DEGURBA" / "hojas" / "1975"

In [45]:
df = pd.read_excel(year_path / "normal.xlsx")

temp = df.loc[lambda df: df["pop_urban_cluster_1975"] > 0]
temp_in_amazon = temp.loc[lambda df: df["in_amazon"] == "yes"].assign(
    pop_1975_edit=lambda df: (
        df["pop_urban_cluster_1975"]
        + df["pop_urban_center_1975"]
        + df["pop_rural_1975"]
    )
)
temp_out_amazon = temp.loc[lambda df: df["in_amazon"] == "no"].assign(
    pop_1975_edit=lambda df: df["pop_urban_cluster_1975"] + df["pop_urban_center_1975"]
)

temp_normal = pd.concat([temp_in_amazon, temp_out_amazon]).loc[
    lambda df: df["pop_1975_edit"] > 5000
]

In [46]:
df = pd.read_excel(year_path / "sin_conurb.xlsx")

temp = df.loc[lambda df: df["pop_urban_cluster_1975"] > 0]
temp_in_amazon = temp.loc[lambda df: df["in_amazon"]].assign(
    pop_1975_edit=lambda df: (
        df["pop_urban_cluster_1975"]
        + df["pop_urban_center_1975"]
        + df["pop_rural_1975"]
    )
)
temp_out_amazon = temp.loc[lambda df: ~df["in_amazon"]].assign(
    pop_1975_edit=lambda df: df["pop_urban_cluster_1975"] + df["pop_urban_center_1975"]
)

temp_sin_conurb = pd.concat([temp_in_amazon, temp_out_amazon]).loc[
    lambda df: df["pop_1975_edit"] > 5000
]

In [47]:
temp_normal

,polygon_id,GID_0,GID_1,GID_2,GID_3,GID_4,NAME_0,NAME_1,NAME_2,NAME_3,...,pop_urban_center_1975,pop_urban_cluster_1975,pop_rural_1975,area_km2,density_1975,in_amazon,area_rural_km2,area_urban_center_km2,area_urban_cluster_km2,pop_1975_edit
28626,p049804,VEN,VEN.9_1,VEN.9.4_1,NaN,NaN,Venezuela,Delta Amacuro,Tucupita,NaN,...,0.000000,10958.109471,1431.952668,21,590.002959,yes,7,0,14,12390.062139
28635,p050392,VEN,VEN.17_1+VEN.2_1+VEN.6_1,VEN.17.12_1+VEN.2.12_1+VEN.6.2_1,NaN,NaN,Venezuela,Anzoátegui+Bolívar+Monagas,Caroní+Independencia+Sotillo,NaN,...,0.000000,50910.764930,9691.768393,59,1027.161582,yes,37,0,22,60602.533322
28644,p050443,VEN,VEN.2_1+VEN.6_1,VEN.2.12_1+VEN.6.2_1,NaN,NaN,Venezuela,Anzoátegui+Bolívar,Caroní+Independencia,NaN,...,299058.209476,24820.535875,4200.369784,75,4374.388202,yes,12,36,27,328079.115135
28654,p050537,VEN,VEN.2_1+VEN.6_1,VEN.2.12_1+VEN.6.6_1,NaN,NaN,Venezuela,Anzoátegui+Bolívar,Heres+Independencia,NaN,...,0.000000,16130.174410,2362.413878,22,840.572195,yes,8,0,14,18492.588288
28658,p050567,VEN,VEN.2_1+VEN.6_1,VEN.2.12_1+VEN.6.6_1,NaN,NaN,Venezuela,Anzoátegui+Bolívar,Heres+Independencia,NaN,...,133535.443584,11088.498393,1420.631580,70,2086.351051,yes,7,47,16,146044.573557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28611,p032321,ARG,ARG.20_1,ARG.20.3_1,NaN,NaN,Argentina,Santa Cruz,Güer Aike,NaN,...,0.000000,33491.184230,468.306193,28,1212.838944,no,2,0,26,33491.184230
28612,p032322,CHL,CHL.11_1,CHL.11.4_1,CHL.11.4.1_1,NaN,Chile,Magallanes y Antártica Chilena,Última Esperanza,Natales,...,0.000000,15677.289841,0.000000,8,1959.661230,no,0,0,8,15677.289841
28617,p032327,CHL,CHL.11_1,CHL.11.2_1,CHL.11.2.2_1,NaN,Chile,Magallanes y Antártica Chilena,Magallanes,Punta Arenas,...,116113.573775,4986.559809,257.661740,28,4334.206976,no,1,18,9,121100.133584
28619,p032329,ARG,ARG.23_1,ARG.23.1_1,NaN,NaN,Argentina,Tierra del Fuego,Rió Grande,NaN,...,0.000000,7425.066509,124.046722,15,503.274215,no,1,0,14,7425.066509
28621,p032331,ARG,ARG.23_1,ARG.23.2_1,NaN,NaN,Argentina,Tierra del Fuego,Ushuaia,NaN,...,0.000000,7031.267927,675.370249,13,592.818321,no,3,0,10,7031.267927

In [48]:
temp_sin_conurb

,name,max_name,in_amazon,NAME_0,NAME_1,NAME_2,NAME_3,NAME_4,GID_0,GID_1,...,pop_1975,pop_rural_1975,pop_urban_cluster_1975,pop_urban_center_1975,area_km2,density_1975,area_rural_km2,area_urban_center_km2,area_urban_cluster_km2,pop_1975_edit
28678,Tucupita,Tucupita,True,Venezuela,Delta Amacuro,Tucupita,NaN,NaN,VEN,VEN.9_1,...,12390.062139,1431.952668,10958.109471,0.000000,21,590.002959,7.0,0.0,14.0,12390.062139
28687,San Félix,San Félix,True,Venezuela,Anzoátegui+Bolívar+Monagas,Caroní+Independencia+Sotillo,NaN,NaN,VEN,VEN.17_1+VEN.2_1+VEN.6_1,...,60602.533322,9691.768393,50910.764930,0.000000,59,1027.161582,37.0,0.0,22.0,60602.533322
28696,Puerto Ordaz+Ciudad Guayana,Ciudad Guayana,True,Venezuela,Anzoátegui+Bolívar,Caroní+Independencia,NaN,NaN,VEN,VEN.2_1+VEN.6_1,...,328079.115135,4200.369784,24820.535875,299058.209476,75,4374.388202,12.0,36.0,27.0,328079.115135
28706,Cerca de Ciudad Bolívar,Cerca de Ciudad Bolívar,True,Venezuela,Anzoátegui+Bolívar,Heres+Independencia,NaN,NaN,VEN,VEN.2_1+VEN.6_1,...,18492.588288,2362.413878,16130.174410,0.000000,22,840.572195,8.0,0.0,14.0,18492.588288
28710,Ciudad Bolívar,Ciudad Bolívar,True,Venezuela,Anzoátegui+Bolívar,Heres+Independencia,NaN,NaN,VEN,VEN.2_1+VEN.6_1,...,146044.573557,1420.631580,11088.498393,133535.443584,70,2086.351051,7.0,47.0,16.0,146044.573557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28663,Río Gallegos,Río Gallegos,False,Argentina,Santa Cruz,Güer Aike,NaN,NaN,ARG,ARG.20_1,...,33959.490423,468.306193,33491.184230,0.000000,28,1212.838944,2.0,0.0,26.0,33491.184230
28664,Puerto Natales,Puerto Natales,False,Chile,Magallanes y Antártica Chilena,Última Esperanza,Natales,NaN,CHL,CHL.11_1,...,15677.289841,0.000000,15677.289841,0.000000,8,1959.661230,0.0,0.0,8.0,15677.289841
28669,Punta Arenas,Punta Arenas,False,Chile,Magallanes y Antártica Chilena,Magallanes,Punta Arenas,NaN,CHL,CHL.11_1,...,121357.795324,257.661740,4986.559809,116113.573775,28,4334.206976,1.0,18.0,9.0,121100.133584
28671,Río Grande,Río Grande,False,Argentina,Tierra del Fuego,Rió Grande,NaN,NaN,ARG,ARG.23_1,...,7549.113231,124.046722,7425.066509,0.000000,15,503.274215,1.0,0.0,13.0,7425.066509
28673,Ushuaia,Ushuaia,False,Argentina,Tierra del Fuego,Ushuaia,NaN,NaN,ARG,ARG.23_1,...,7706.638176,675.370249,7031.267927,0.000000,13,592.818321,3.0,0.0,10.0,7031.267927